fix: Stripe payment not working
v2board/v2board pull request #972
Opened 2023-10-26 05:04 UTC by missuo

The previous exchange rate conversion API has been tested and is no longer free. It now requires an **API Key**. 

**This PR has been replaced with the currently available free exchange rate conversion API.**

2023-12-09 10:01 UTC, lslzl3000 commented
how to set up stripe? I can't find any tutorial or doc

2023-12-09 14:44 UTC, TheMrJC approved these changes
It fixed the Stripe problem, well done @missuo

2023-12-10 09:33 UTC, lslzl3000 commented
@TheMrJC what is the stripe webhook callback url? I can't find any doc about this.

2023-12-10 09:35 UTC, missuo commented
> @TheMrJC what is the stripe webhook callback url? I can't find any doc about this.

Read the official Stripe documentation carefully.

2023-12-10 09:47 UTC, lslzl3000 commented
> > @TheMrJC what is the stripe webhook callback url? I can't find any doc about this.
> 
> Read the official Stripe documentation carefully.

I think the webhook url should be provided by v2board side
e.g. if v2board site is host at `https://domain.com`
the webhook should be a specific path, e.g. `https://domain.com/payment/stripe/notice` ?

But I can't find any doc about the callback path,  and there are several payments method for stripe, are they share the same webhook url? or different path for each method?

2023-12-10 09:52 UTC, missuo commented
> > > @TheMrJC what is the stripe webhook callback url? I can't find any doc about this.
> > 
> > Read the official Stripe documentation carefully.
> 
> I think the webhook url should be provided by v2board side
> e.g. if v2board site is host at `https://domain.com`
> the webhook should be a specific path, e.g. `https://domain.com/payment/stripe/notice` ?
> 
> But I can't find any doc about the callback path,  and there are several payments method for stripe, are they share the same webhook url? or different path for each method?

After you add the payment method in v2board, you will find that a callback address is automatically generated.

2023-12-10 09:59 UTC, lslzl3000 commented
> > > > @TheMrJC what is the stripe webhook callback url? I can't find any doc about this.
> > > 
> > > 
> > > Read the official Stripe documentation carefully.
> > 
> > 
> > I think the webhook url should be provided by v2board side
> > e.g. if v2board site is host at `https://domain.com`
> > the webhook should be a specific path, e.g. `https://domain.com/payment/stripe/notice` ?
> > But I can't find any doc about the callback path,  and there are several payments method for stripe, are they share the same webhook url? or different path for each method?
> 
> After you add the payment method in v2board, you will find that a callback address is automatically generated.

ok~~  thanks, finally got the url
the trick is to get a webhook secret, you need to fill a webhook url in advance. so I will keep finding the url before add a payment method.

2023-12-11 13:24 UTC, lslzl3000 commented
@missuo I tried this new stripeCheckout.php, but it only shows error with 500 status, is there any way to show the error details?

2023-12-15 02:45 UTC, lslzl3000 commented
I got one interesting question, if set a price with a small number, e.g. ￥0.1 or ￥1，the `api/v1/user/order/checkout` will fail with an error.
How to debug this?  the error message does not show details.  is this a stripe problem or v2board setting?

2023-12-15 23:56 UTC, missuo commented
I can assure you that this PR fixes the bug where Stripe can't process payments. As for the issues you mentioned, you should try to solve them yourself. @lslzl3000

2023-12-19 08:49 UTC, WhoCaresBugs commented
![屏幕截图 2023-12-19 164620](https://github.com/v2board/v2board/assets/150936032/3a3a196b-38d0-4f8a-81c2-ee418367c956)

1.7.4版本，在輸入信用卡號的時候，出錯。umi.js?v=1.7.4.1681103823832:1  Unsupported prop change on Elements: You cannot change the `stripe` prop after setting it. 無法提交並閉環支付

2024-01-28 05:55 UTC, mmsh1370 commented
Hello I tried to install two front panels in one VPS by Aappnel The problem I encounter is that users' traffic is recorded irregularly in both databases and both fronts. That is, if user number 9 is online from the first panel, it will show him online in the second panel, even if no node or subscription is defined for the second panel. Can you guide me how to install several fronts on one VPS without any problems?
I am using V2Board v1.7.2
I couldn't open a new request, that's why I left a comment here 
Thank you for helping me

2024-02-05 06:02 UTC, NiuBiDeXiaoLinGe commented
数据库备份了，面板迁移到新服务器，然后导入数据库，之前部分老用户，无法登录，报错我们遇到一些问题，该如何解决？

2024-03-03 07:08 UTC, darwinchow requested changes
It works perfectly now.

2025-12-11 11:22 UTC, closed without merging